feat(ci): create build-binaries upon GitHub Release 👷
nicolaiunrein/cargo-get pull request #4
Opened 2023-08-04 04:02 UTC by meysam81

This PR will create a binary release upon GitHub Release.
You can see an example run [here](https://github.com/meysam81/cargo-get/actions/runs/5758242523) and the result of such run [over here in the Assets section](https://github.com/meysam81/cargo-get/releases/tag/0.1.0).

It allows the users not to have `cargo` installed if they don't want to run the binary using `cargo run`.

2023-08-04 17:36 UTC, nicolaiunrein requested changes
Thank you for your PRs! Just two minor additions for this one.

2023-08-04 17:36 UTC, nicolaiunrein commented on README.md
> +Place the binary in your `$PATH` and rename it to `cargo-get`.
The syntax `cargo get something` only works if it is in the cargo bin directory as far as I am concerned.

2023-08-04 17:36 UTC, nicolaiunrein commented on .github/workflows/build-binary.yml
> +        include:
I think we should add windows to the matrix as well.

2023-08-05 06:38 UTC, nicolaiunrein commented on .github/workflows/build-binary.yml
Unfortunately the package-name step fails on windows because it does not understand unix style syntax for environment variables.

2023-08-05 06:46 UTC, nicolaiunrein requested changes

2023-08-05 06:46 UTC, nicolaiunrein commented on README.md
Sorry, I deleted the comment because I was wrong 😑. It does not need to be in the cargo bin folder. Anywhere in the $PATH works fine. However I still think the bin folder is the preferred place. But I think users will need to change permissions on the file after downloading to make it executable.

2023-08-05 12:54 UTC, meysam81 commented
@nicolaiunrein 
I recommend skipping windows for this PR, as I can't get it to work properly.
Let's just merge this for now if all else looks good, and think about adding a windows build to the same CI file later on.

2023-08-05 13:55 UTC, merged

2023-08-05 13:56 UTC, nicolaiunrein commented
@meysam81 Thank you for your efforts!

2023-08-05 14:10 UTC, meysam81 commented
@nicolaiunrein 
You are very welcome
You'll need to [create a new release](https://github.com/nicolaiunrein/cargo-get/releases/new?marketplace=true) to see the result of this effort in action.

2023-08-05 14:18 UTC, nicolaiunrein commented
I know. I'm just fixing clippy errors and updating dependencies along the way.

2023-08-05 14:31 UTC, nicolaiunrein commented
Just realized why I haven't upgraded dependencies earlier. `cargo_toml` has changed quite a bit. It includes workspaces now and once I upgrade I want to support workspaces as well. I leave this for the future. Maybe in a couple of days. I am on holiday right now and have limited time. For now I made clippy happy and am about to release a new version.

2023-08-05 14:38 UTC, nicolaiunrein commented
I just tried to release to gh marketplace but the name `cargo-get` is already taken. Probably from your fork?

2023-08-05 14:58 UTC, nicolaiunrein commented
The downloaded file from the releases throws an error on my machine while a local build works:
```
./cargo-get-x86_64-unknown-linux-gnu: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./cargo-get-x86_64-unknown-linux-gnu)
./cargo-get-x86_64-unknown-linux-gnu: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./cargo-get-x86_64-unknown-linux-gnu)
./cargo-get-x86_64-unknown-linux-gnu: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./cargo-get-x86_64-unknown-linux-gnu)
```

2023-08-05 15:37 UTC, nicolaiunrein commented
v0.3.5 builds with musl now to avoid this error for users with outdated libc.

2023-08-05 15:59 UTC, meysam81 commented
@nicolaiunrein 
You can also add another pair to the strategy so that there are builds for both gnu and musl

2023-08-05 17:44 UTC, nicolaiunrein commented
would you prefer a gnu build?